version: '3.2'

services:
  portainer:
    image: portainer/portainer
    ports:
      - "10002:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
